#  Print the numpy version and the configuration 

In [9]:
import numpy as np
print(np.__version__)
#np.show_config()

1.14.0


# Finding Memory size of an array

In [10]:
Z = np.ones((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# Create a vector whose fifth value is 1

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49 

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Reverse a vector

In [12]:
Z = np.arange(50)
Z = Z[::-2]
print(Z)

[49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5  3
  1]


# Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from 1,2,0,0,4,0

In [14]:
nz = np.nonzero([1,2,1,1,4,1])
print(nz)

(array([0, 1, 2, 3, 4, 5]),)


# Create a 10x10 array with random values and find the minimum and maximum values 

In [15]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01685151677484742 0.978349133510406


# Create a random vector of size 30 and find the mean value 

In [16]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4661435640980282


# nan Values

In [3]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print( 1.0 == 1.0)

nan
False
False
nan
False
True


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a checkerboard 8x8 matrix using the tile function 

In [23]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Matrix multiplication

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# Given a 1D array, negate all elements which are between 3 and 8, in place

In [27]:
Z = np.arange(11)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


# What is the Output ?

In [4]:
 
print(sum(range(5)))
 
 

10


# How to find common values between two arrays

In [49]:
Z1 = np.array([1,3,5,7,9,11])
Z2 = np.array([1,5,8,9,11,13,14]) 
print(np.intersect1d(Z1,Z2))

[ 1  5  9 11]


In [ ]:
# Dates Yesterday, Today and tomorrow

In [53]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, ",",today,",",tomorrow)

2018-10-03 , 2018-10-04 , 2018-10-05


# Check if two arrays are equal

In [60]:
#A = np.random.randint(0,2,5)
#B = np.random.randint(0,2,5)
A = np.array([1,3.00001,5])
B = np.array([1,3,5])
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

True
False


# Make an array immutable or readonly

In [62]:
Z = np.zeros(10)
#Z.flags.writeable = False
Z[0] = 1

# Enumerate for Numpy arrays

In [64]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
#for index in np.ndindex(Z.shape):
#    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# Swap two rows of an array

In [65]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Inplace substitutions

In [71]:
Z = np.random.randint(0,2,10)
print(Z)   
np.logical_not(Z, out=Z)
print(Z) 
np.negative(Z, out=Z)
print(Z)

[1 1 0 1 1 1 0 0 1 1]
[0 0 1 0 0 0 1 1 0 0]
[ 0  0 -1  0  0  0 -1 -1  0  0]


# Most frequent value in an array

In [77]:
Z = np.random.randint(0,10,6)
print(Z)
print(np.bincount(Z).argmax())

[2 6 3 6 6 4]
6


### Reference : https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb