### Creating Dummies

pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)[source]
Convert categorical variable into dummy/indicator variables

## Parameters

data : array-like, Series, or DataFrame
prefix : string, list of strings, or dict of strings, default None

String to append DataFrame column names. Pass a list with length equal to the number of columns when calling get_dummies on a DataFrame. Alternatively, prefix can be a dictionary mapping column names to prefixes.

prefix_sep : string, default ‘_’

If appending prefix, separator/delimiter to use. Or pass a list or dictionary as with prefix.

dummy_na : bool, default False

Add a column to indicate NaNs, if False NaNs are ignored.

columns : list-like, default None

Column names in the DataFrame to be encoded. If columns is None then all the columns with object or category dtype will be converted.

sparse : bool, default False

Whether the dummy columns should be sparse or not. Returns SparseDataFrame if data is a Series or if all columns are included. Otherwise returns a DataFrame with some SparseBlocks.

drop_first : bool, default False

Whether to get k-1 dummies out of k categorical levels by removing the first level.

New in version 0.18.0.
 dtype : dtype, default np.uint8

Data type for new columns. Only a single dtype is allowed.

New in version 0.23.0.

# Returns
dummies : DataFrame or SparseDataFrame

In [2]:
import pandas as pd
s = pd.Series(list('abca'))

In [3]:
s

0    a
1    b
2    c
3    a
dtype: object

In [4]:
pd.get_dummies(s)

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [5]:
import numpy as np
s1 = ['a', 'b', np.nan]

In [6]:
s1

['a', 'b', nan]

In [7]:
pd.get_dummies(s1)

a  b
0  1  0
1  0  1
2  0  0

In [27]:
pd.get_dummies(s1, dummy_na=True)

a  b  NaN
0  1  0    0
1  0  1    0
2  0  0    1

In [28]:
df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
...                    'C': [1, 2, 3]})

In [29]:
df

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [31]:
pd.get_dummies(df)

C  A_a  A_b  B_a  B_b  B_c
0  1    1    0    0    1    0
1  2    0    1    1    0    0
2  3    1    0    0    0    1

In [30]:
pd.get_dummies(df, prefix=['col1', 'col2'])

C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1       1       0       0       1       0
1  2       0       1       1       0       0
2  3       1       0       0       0       1

In [39]:
s = pd.Series(list('abcaa'))

In [40]:
s

0    a
1    b
2    c
3    a
4    a
dtype: object

In [42]:
pd.get_dummies(s)

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0
4  1  0  0

In [43]:
pd.get_dummies(s, drop_first=True)

b  c
0  0  0
1  1  0
2  0  1
3  0  0
4  0  0

## Getting Unique values


This method is useful for obtaining a numeric representation of an array when all that matters is identifying distinct values. factorize is available as both a top-level function pandas.factorize(), and as a method Series.factorize() and Index.factorize().

In [10]:
labels, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b', 'test'])

In [11]:
print(uniques)

['b' 'a' 'c' 'test']


In [12]:
print(labels)

[0 0 1 2 0 3]


In [51]:
labels, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'], sort=True) #

In [ ]:
## With sort=True, the uniques will be sorted, and labels will be shuffled so that the relationship is the maintained.

In [52]:
print(uniques)

['a' 'b' 'c']


In [53]:
print(labels)

[1 1 0 2 1]


In [54]:
labels, uniques = pd.factorize(['b', None, 'a', 'c', 'b'])

In [56]:
print(uniques)

['b' 'a' 'c']


In [57]:
print(labels)

[ 0 -1  1  2  0]


Missing values are indicated in labels with na_sentinel (-1 by default). Note that missing values are never included in uniques.

## Uniques for dataframes

In [13]:
cat = pd.Categorical(['a', 'a', 'c'], categories=['a', 'b', 'c'])

In [14]:
print(cat)

[a, a, c]
Categories (3, object): [a, b, c]


In [15]:
labels, uniques = pd.factorize(cat)

In [16]:
print(uniques)

[0 2]


In [17]:
labels

array([0, 0, 1])

In [67]:
pd.unique([('a', 'b'), ('b', 'a'), ('a', 'c'), ('b', 'a')])
 

array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)

In [20]:
import pandas as pd
df = pd.read_csv("salarydat.csv",header=0)

In [21]:
df

sx         rk  yr         dg  yd     sl
0     male       full  25  doctorate  35  36350
1     male       full  13  doctorate  22  35350
2     male       full  10  doctorate  23  28200
3   female       full   7  doctorate  27  26775
4     male       full  19    masters  30  33696
5     male       full  16  doctorate  21  28516
6   female       full   0    masters  32  24900
7     male       full  16  doctorate  18  31909
8     male       full  13    masters  30  31850
9     male       full  13    masters  31  32850
10    male       full  12  doctorate  22  27025
11    male  associate  15  doctorate  19  24750
12    male       full   9  doctorate  17  28200
13    male  associate   9    masters  27  23712
14    male       full   9  doctorate  24  25748
15    male       full   7  doctorate  15  29342
16    male       full  13  doctorate  20  31114
17    male  associate  11    masters  14  24742
18    male  associate  10    masters  15  22906
19    male       full   6    masters  21  24450
20    male  assistant  16    masters  23  19175
21    male  associate   8    masters  31  20525
22    male       full   7  doctorate  13  27959
23  female       full   8  doctorate  24  38045
24    male  associate   9  doctorate  12  24832
25    male       full   5  doctorate  18  25400
26    male  associate  11  doctorate  14  24800
27  female       full   5  doctorate  16  25500
28    male  associate   3    masters   7  26182
29    male  associate   3    masters  17  23725
30  female  assistant  10    masters  15  21600
31    male  associate  11    masters  31  23300
32    male  assistant   9    masters  14  23713
33  female  associate   4    masters  33  20690
34  female  associate   6    masters  29  22450
35    male  associate   1  doctorate   9  20850
36  female  assistant   8  doctorate  14  18304
37    male  assistant   4  doctorate   4  17095
38    male  assistant   4  doctorate   5  16700
39    male  assistant   4  doctorate   4  17600
40    male  assistant   3  doctorate   4  18075
41    male  assistant   3    masters  11  18000
42    male  associate   0  doctorate   7  20999
43  female  assistant   3  doctorate   3  17250
44    male  assistant   2  doctorate   3  16500
45    male  assistant   2  doctorate   1  16094
46  female  assistant   2  doctorate   6  16150
47  female  assistant   2  doctorate   2  15350
48    male  assistant   1  doctorate   1  16244
49  female  assistant   1  doctorate   1  16686
50  female  assistant   1  doctorate   1  15000
51  female  assistant   0  doctorate   2  20300

In [9]:
df.head()

sx    rk  yr         dg  yd     sl
0    male  full  25  doctorate  35  36350
1    male  full  13  doctorate  22  35350
2    male  full  10  doctorate  23  28200
3  female  full   7  doctorate  27  26775
4    male  full  19    masters  30  33696

In [22]:
dummy = pd.get_dummies(df['sx'])

In [11]:
dummy

female  male
0        0     1
1        0     1
2        0     1
3        1     0
4        0     1
5        0     1
6        1     0
7        0     1
8        0     1
9        0     1
10       0     1
11       0     1
12       0     1
13       0     1
14       0     1
15       0     1
16       0     1
17       0     1
18       0     1
19       0     1
20       0     1
21       0     1
22       0     1
23       1     0
24       0     1
25       0     1
26       0     1
27       1     0
28       0     1
29       0     1
30       1     0
31       0     1
32       0     1
33       1     0
34       1     0
35       0     1
36       1     0
37       0     1
38       0     1
39       0     1
40       0     1
41       0     1
42       0     1
43       1     0
44       0     1
45       0     1
46       1     0
47       1     0
48       0     1
49       1     0
50       1     0
51       1     0

In [23]:
dummy = pd.get_dummies(df['dg'])

In [24]:
df=pd.concat((df,dummy),axis=1)

In [15]:
df

sx         rk  yr         dg  yd     sl  doctorate  masters
0     male       full  25  doctorate  35  36350          1        0
1     male       full  13  doctorate  22  35350          1        0
2     male       full  10  doctorate  23  28200          1        0
3   female       full   7  doctorate  27  26775          1        0
4     male       full  19    masters  30  33696          0        1
5     male       full  16  doctorate  21  28516          1        0
6   female       full   0    masters  32  24900          0        1
7     male       full  16  doctorate  18  31909          1        0
8     male       full  13    masters  30  31850          0        1
9     male       full  13    masters  31  32850          0        1
10    male       full  12  doctorate  22  27025          1        0
11    male  associate  15  doctorate  19  24750          1        0
12    male       full   9  doctorate  17  28200          1        0
13    male  associate   9    masters  27  23712          0        1
14    male       full   9  doctorate  24  25748          1        0
15    male       full   7  doctorate  15  29342          1        0
16    male       full  13  doctorate  20  31114          1        0
17    male  associate  11    masters  14  24742          0        1
18    male  associate  10    masters  15  22906          0        1
19    male       full   6    masters  21  24450          0        1
20    male  assistant  16    masters  23  19175          0        1
21    male  associate   8    masters  31  20525          0        1
22    male       full   7  doctorate  13  27959          1        0
23  female       full   8  doctorate  24  38045          1        0
24    male  associate   9  doctorate  12  24832          1        0
25    male       full   5  doctorate  18  25400          1        0
26    male  associate  11  doctorate  14  24800          1        0
27  female       full   5  doctorate  16  25500          1        0
28    male  associate   3    masters   7  26182          0        1
29    male  associate   3    masters  17  23725          0        1
30  female  assistant  10    masters  15  21600          0        1
31    male  associate  11    masters  31  23300          0        1
32    male  assistant   9    masters  14  23713          0        1
33  female  associate   4    masters  33  20690          0        1
34  female  associate   6    masters  29  22450          0        1
35    male  associate   1  doctorate   9  20850          1        0
36  female  assistant   8  doctorate  14  18304          1        0
37    male  assistant   4  doctorate   4  17095          1        0
38    male  assistant   4  doctorate   5  16700          1        0
39    male  assistant   4  doctorate   4  17600          1        0
40    male  assistant   3  doctorate   4  18075          1        0
41    male  assistant   3    masters  11  18000          0        1
42    male  associate   0  doctorate   7  20999          1        0
43  female  assistant   3  doctorate   3  17250          1        0
44    male  assistant   2  doctorate   3  16500          1        0
45    male  assistant   2  doctorate   1  16094          1        0
46  female  assistant   2  doctorate   6  16150          1        0
47  female  assistant   2  doctorate   2  15350          1        0
48    male  assistant   1  doctorate   1  16244          1        0
49  female  assistant   1  doctorate   1  16686          1        0
50  female  assistant   1  doctorate   1  15000          1        0
51  female  assistant   0  doctorate   2  20300          1        0

In [16]:
df=df.merge(dummy, left_index=True,right_index=True)

In [17]:
df

sx         rk  yr         dg  yd     sl  doctorate_x  masters_x  \
0     male       full  25  doctorate  35  36350            1          0   
1     male       full  13  doctorate  22  35350            1          0   
2     male       full  10  doctorate  23  28200            1          0   
3   female       full   7  doctorate  27  26775            1          0   
4     male       full  19    masters  30  33696            0          1   
5     male       full  16  doctorate  21  28516            1          0   
6   female       full   0    masters  32  24900            0          1   
7     male       full  16  doctorate  18  31909            1          0   
8     male       full  13    masters  30  31850            0          1   
9     male       full  13    masters  31  32850            0          1   
10    male       full  12  doctorate  22  27025            1          0   
11    male  associate  15  doctorate  19  24750            1          0   
12    male       full   9  doctorate  17  28200            1          0   
13    male  associate   9    masters  27  23712            0          1   
14    male       full   9  doctorate  24  25748            1          0   
15    male       full   7  doctorate  15  29342            1          0   
16    male       full  13  doctorate  20  31114            1          0   
17    male  associate  11    masters  14  24742            0          1   
18    male  associate  10    masters  15  22906            0          1   
19    male       full   6    masters  21  24450            0          1   
20    male  assistant  16    masters  23  19175            0          1   
21    male  associate   8    masters  31  20525            0          1   
22    male       full   7  doctorate  13  27959            1          0   
23  female       full   8  doctorate  24  38045            1          0   
24    male  associate   9  doctorate  12  24832            1          0   
25    male       full   5  doctorate  18  25400            1          0   
26    male  associate  11  doctorate  14  24800            1          0   
27  female       full   5  doctorate  16  25500            1          0   
28    male  associate   3    masters   7  26182            0          1   
29    male  associate   3    masters  17  23725            0          1   
30  female  assistant  10    masters  15  21600            0          1   
31    male  associate  11    masters  31  23300            0          1   
32    male  assistant   9    masters  14  23713            0          1   
33  female  associate   4    masters  33  20690            0          1   
34  female  associate   6    masters  29  22450            0          1   
35    male  associate   1  doctorate   9  20850            1          0   
36  female  assistant   8  doctorate  14  18304            1          0   
37    male  assistant   4  doctorate   4  17095            1          0   
38    male  assistant   4  doctorate   5  16700            1          0   
39    male  assistant   4  doctorate   4  17600            1          0   
40    male  assistant   3  doctorate   4  18075            1          0   
41    male  assistant   3    masters  11  18000            0          1   
42    male  associate   0  doctorate   7  20999            1          0   
43  female  assistant   3  doctorate   3  17250            1          0   
44    male  assistant   2  doctorate   3  16500            1          0   
45    male  assistant   2  doctorate   1  16094            1          0   
46  female  assistant   2  doctorate   6  16150            1          0   
47  female  assistant   2  doctorate   2  15350            1          0   
48    male  assistant   1  doctorate   1  16244            1          0   
49  female  assistant   1  doctorate   1  16686            1          0   
50  female  assistant   1  doctorate   1  15000            1          0   
51  female  assistant   0  doctorate   2  20300            1          0   

    doctorate_y  masters_y  
0  